import Foundation

// MARK: - CoachProfile

/// Persistent coaching profile that summarizes what the coach "knows"
/// about the user's training preferences and patterns.
///
/// Updated incrementally after each workout and weekly recap.
/// Synced through the existing data layer (CloudKit or Local).
public struct CoachProfile: Codable, Sendable {
    /// Preferred session duration in minutes (learned from history).
    public var preferredSessionMinutes: Int

    /// Most frequently chosen focus areas, ordered by frequency.
    public var preferredFocusAreas: [String]

    /// Most frequently used equipment setting.
    public var preferredEquipment: String

    /// Exercises the user selects often (top 10).
    public var favoriteExercises: [String]

    /// Exercises the user skips, swaps away from, or removes during edits.
    public var avoidedExercises: [String]

    /// Average workouts per week (rolling 4-week).
    public var avgWorkoutsPerWeek: Double

    /// Typical energy level distribution (low/medium/high counts).
    public var energyDistribution: EnergyDistribution

    /// Total workouts the coach has observed.
    public var totalWorkoutsObserved: Int

    /// When this profile was last updated.
    public var lastUpdated: Date

    public init(
        preferredSessionMinutes: Int = 45,
        preferredFocusAreas: [String] = [],
        preferredEquipment: String = "full_gym",
        favoriteExercises: [String] = [],
        avoidedExercises: [String] = [],
        avgWorkoutsPerWeek: Double = 0,
        energyDistribution: EnergyDistribution = EnergyDistribution(),
        totalWorkoutsObserved: Int = 0,
        lastUpdated: Date = Date()
    ) {
        self.preferredSessionMinutes = preferredSessionMinutes
        self.preferredFocusAreas = preferredFocusAreas
        self.preferredEquipment = preferredEquipment
        self.favoriteExercises = favoriteExercises
        self.avoidedExercises = avoidedExercises
        self.avgWorkoutsPerWeek = avgWorkoutsPerWeek
        self.energyDistribution = energyDistribution
        self.totalWorkoutsObserved = totalWorkoutsObserved
        self.lastUpdated = lastUpdated
    }
}

// MARK: - EnergyDistribution

/// Tracks how often the user reports each energy level.
public struct EnergyDistribution: Codable, Sendable {
    public var lowCount: Int
    public var mediumCount: Int
    public var highCount: Int

    public init(lowCount: Int = 0, mediumCount: Int = 0, highCount: Int = 0) {
        self.lowCount = lowCount
        self.mediumCount = mediumCount
        self.highCount = highCount
    }

    /// The most common energy level.
    public var dominant: EnergyLevel {
        if highCount >= mediumCount && highCount >= lowCount { return .high }
        if lowCount >= mediumCount { return .low }
        return .medium
    }

    public var total: Int { lowCount + mediumCount + highCount }
}

// MARK: - AcceptedSubstitution

/// Records a substitution decision (accepted or rejected) for learning.
public struct AcceptedSubstitution: Codable, Sendable {
    /// The original exercise that was substituted.
    public let originalExercise: String

    /// The substitute that was offered.
    public let substituteExercise: String

    /// Whether the user accepted this substitution.
    public let accepted: Bool

    /// Why the substitution was suggested (injury, equipment, preference).
    public let reason: String

    /// When the decision was made.
    public let date: Date

    public init(
        originalExercise: String,
        substituteExercise: String,
        accepted: Bool,
        reason: String,
        date: Date = Date()
    ) {
        self.originalExercise = originalExercise
        self.substituteExercise = substituteExercise
        self.accepted = accepted
        self.reason = reason
        self.date = date
    }
}

// MARK: - CoachWeeklySummary

/// A rolling weekly summary generated by the coach memory system.
public struct CoachWeeklySummary: Codable, Sendable {
    /// The Monday that starts this week.
    public let weekStartDate: Date

    /// Number of workouts completed.
    public let workoutsCompleted: Int

    /// Total training minutes.
    public let totalMinutes: Int

    /// Muscle groups trained this week.
    public let muscleGroupsHit: [String]

    /// Key observations (e.g., "skipped legs this week", "3 PRs").
    public let observations: [String]

    /// Recommendations for the next week.
    public let recommendations: [String]

    /// When this summary was generated.
    public let generatedAt: Date

    public init(
        weekStartDate: Date,
        workoutsCompleted: Int,
        totalMinutes: Int,
        muscleGroupsHit: [String],
        observations: [String],
        recommendations: [String],
        generatedAt: Date = Date()
    ) {
        self.weekStartDate = weekStartDate
        self.workoutsCompleted = workoutsCompleted
        self.totalMinutes = totalMinutes
        self.muscleGroupsHit = muscleGroupsHit
        self.observations = observations
        self.recommendations = recommendations
        self.generatedAt = generatedAt
    }
}

// MARK: - WorkoutEdit

/// Records an edit the user made to a generated workout.
/// Used to learn what the user changes and avoid suggesting it again.
public struct WorkoutEdit: Codable, Sendable {
    public enum EditType: String, Codable, Sendable {
        /// User removed an exercise from the workout.
        case removedExercise
        /// User swapped one exercise for another.
        case swappedExercise
        /// User changed the prescribed weight.
        case changedWeight
        /// User changed sets or reps.
        case changedVolume
    }

    /// What kind of edit was made.
    public let editType: EditType

    /// The exercise that was affected.
    public let exerciseName: String

    /// For swaps: the replacement exercise (nil otherwise).
    public let replacementExercise: String?

    /// When the edit was made.
    public let date: Date

    public init(
        editType: EditType,
        exerciseName: String,
        replacementExercise: String? = nil,
        date: Date = Date()
    ) {
        self.editType = editType
        self.exerciseName = exerciseName
        self.replacementExercise = replacementExercise
        self.date = date
    }
}
