-- Migration number: 0003 generated by teenybase on 2026-04-11T12:47:18.191Z. Do not modify this file.

CREATE TABLE exercises (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	name TEXT NOT NULL, 
	category TEXT NOT NULL, 
	bodyweight BOOLEAN DEFAULT 0, 
	equipment TEXT, 
	movementTags TEXT, 
	status TEXT DEFAULT "draft", 
	sortOrder INTEGER DEFAULT 0
);
CREATE INDEX idx_exercises_status ON exercises (status COLLATE NOCASE);
CREATE INDEX idx_exercises_category ON exercises (category COLLATE NOCASE);
CREATE TRIGGER tgr_exercises_raise_on_created_update BEFORE UPDATE OF created ON exercises BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;