-- Migration number: 0004 generated by teenybase on 2026-04-11T12:26:04.871Z. Do not modify this file.

CREATE TABLE programs (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	name TEXT NOT NULL, 
	templateKey TEXT, 
	category TEXT NOT NULL, 
	description TEXT NOT NULL, 
	durationWeeks INTEGER NOT NULL, 
	sessionsPerWeek INTEGER NOT NULL, 
	difficulty TEXT NOT NULL, 
	phases JSON, 
	status TEXT DEFAULT "draft", 
	version INTEGER DEFAULT 1, 
	sortOrder INTEGER DEFAULT 0
);
CREATE INDEX idx_programs_status ON programs (status COLLATE NOCASE);
CREATE INDEX idx_programs_category ON programs (category COLLATE NOCASE);
CREATE TRIGGER tgr_programs_raise_on_created_update BEFORE UPDATE OF created ON programs BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;