# Project-wide Gradle settings.

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Compose
android.enableComposeCompilerReports=true
android.enableComposeCompilerMetrics=true

# Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Non-transitive R classes
android.nonTransitiveRClass=true
