name = "ai-coach"
main = "src/index.ts"
compatibility_date = "2025-03-28"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "e14b4c63f5cf4c608be882bc0c2b5fca"

[vars]
ENVIRONMENT = "production"
