schemaVersion: 1
enabledWorkflows:
  - simulator
  - coverage
  - debugging
  - device
  - doctor
  - logging
  - macos
  - project-discovery
  - project-scaffolding
  - simulator-management
  - swift-package
  - ui-automation
  - utilities
  - xcode-ide
debug: true
sentryDisabled: true
sessionDefaults:
  projectPath: SundeeFundeeApp/SundeeFundee.xcodeproj
  scheme: SundeeFundee
  deviceId: 415ABB31-3B80-5331-AA90-0B37E4BBDF98
  simulatorId: DCDA29E0-3F11-4C64-BBD1-3605F776BBC5
  simulatorName: iPhone 17 Pro
