package com.sundeefundee.core.data.supabase

import com.sundeefundee.core.data.protocol.DataClient
import com.sundeefundee.core.data.protocol.Predicate
import com.sundeefundee.core.data.protocol.SortDescriptor
import com.sundeefundee.core.model.*
import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.postgrest.from
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import javax.inject.Inject
import javax.inject.Singleton

// Supabase-backed DataClient for authenticated users — mirrors iOS CloudKitClient
@Singleton
class SupabaseDataClient @Inject constructor() : DataClient {

    // Placeholder — will be replaced with real Supabase config when ready
    private val client: SupabaseClient by lazy {
        io.github.jan.supabase.createSupabaseClient(
            supabaseUrl = "https://placeholder.supabase.co",
            supabaseKey = "placeholder-key"
        ) {
            install(io.github.jan.supabase.postgrest.Postgrest)
        }
    }

    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }

    @Suppress("UNCHECKED_CAST")
    override suspend fun <T : Any> fetch(
        recordType: String,
        predicate: Predicate,
        sortDescriptors: List<SortDescriptor>?
    ): List<T> {
        val table = SupabaseSchema.recordTypeToTable[recordType] ?: return emptyList()
        val query = client.from(table).select()
        val result = query.decodeList<JsonObject>()
        val serializer = serializerFor(recordType) ?: return emptyList()

        return result.mapNotNull { row ->
            try {
                json.decodeFromString(serializer as KSerializer<T>, row.toString())
            } catch (_: Exception) {
                null // skip corrupt records, mirrors iOS CloudKitClient
            }
        }
    }

    override suspend fun <T : Any> fetchAll(
        recordType: String,
        sortDescriptors: List<SortDescriptor>?
    ): List<T> {
        return fetch(recordType, Predicate.all, sortDescriptors)
    }

    override suspend fun <T : Any> save(records: List<T>, recordType: String) {
        val table = SupabaseSchema.recordTypeToTable[recordType] ?: return
        for (record in records) {
            save(record, recordType)
        }
    }

    @Suppress("UNCHECKED_CAST")
    override suspend fun <T : Any> save(record: T, recordType: String) {
        val table = SupabaseSchema.recordTypeToTable[recordType] ?: return
        val serializer = serializerFor(recordType) ?: return
        val jsonStr = json.encodeToString(serializer as KSerializer<T>, record)
        client.from(table).upsert(jsonStr)
    }

    override suspend fun delete(recordIds: List<String>, recordType: String) {
        val table = SupabaseSchema.recordTypeToTable[recordType] ?: return
        for (id in recordIds) {
            client.from(table).delete {
                filter { eq("id", id) }
            }
        }
    }

    override suspend fun deleteAllData() {
        val tables = SupabaseSchema.recordTypeToTable.values
        for (table in tables) {
            try {
                client.from(table).delete {}
            } catch (_: Exception) { /* skip tables that don't exist yet */ }
        }
    }

    override suspend fun saveFromJSON(jsonRecords: List<String>, recordType: String) {
        val table = SupabaseSchema.recordTypeToTable[recordType] ?: return
        for (jsonStr in jsonRecords) {
            try {
                client.from(table).upsert(jsonStr)
            } catch (_: Exception) { /* skip malformed records */ }
        }
    }

    companion object {
        /**
         * Returns the KSerializer for a given record type string.
         * Uses the companion serializer() generated by @Serializable.
         */
        @Suppress("UNCHECKED_CAST")
        fun serializerFor(recordType: String): KSerializer<*>? = when (recordType) {
            "Workout" -> Workout.serializer()
            "OneRepMaxRecord" -> OneRepMaxRecord.serializer()
            "Challenge" -> Challenge.serializer()
            "Injury" -> Injury.serializer()
            "DailyPainLog" -> DailyPainLog.serializer()
            "EnrolledProgram" -> EnrolledProgramRecord.serializer()
            "BenchmarkResult" -> BenchmarkResult.serializer()
            "CycleSettings" -> CycleSettings.serializer()
            "PeriodLogRecord" -> PeriodLogRecord.serializer()
            "UserSettings" -> UserSettings.serializer()
            "CyclePhaseInfo" -> CyclePhaseInfo.serializer()
            "CelebrationEventRecord" -> CelebrationEventRecord.serializer()
            "RecoveryScore" -> RecoveryScoreRecord.serializer()
            "CompletedWorkoutRecord" -> CompletedWorkoutRecord.serializer()
            else -> null
        }
    }
}
