// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdeSzyQoOZNHWPfC-DJL_0BfSD64WwCyU',
    appId: '1:23636367470:web:f561f7d2082c0c37f66e7f',
    messagingSenderId: '23636367470',
    projectId: 'sundee-fundee',
    authDomain: 'sundee-fundee.firebaseapp.com',
    storageBucket: 'sundee-fundee.firebasestorage.app',
    measurementId: 'G-HQ8NDR50YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnIKrSyJIZ-aLbEQtbeEJ5fk0_CapNdc',
    appId: '1:23636367470:android:34e638bcb4c7eadbf66e7f',
    messagingSenderId: '23636367470',
    projectId: 'sundee-fundee',
    storageBucket: 'sundee-fundee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0xaQySawc_MXrbuLcEW2vcdYzL8Ymd5s',
    appId: '1:23636367470:ios:35dce13a6a4022b5f66e7f',
    messagingSenderId: '23636367470',
    projectId: 'sundee-fundee',
    storageBucket: 'sundee-fundee.firebasestorage.app',
    iosBundleId: 'com.sundeefundee.app',
  );
}
